#!/usr/bin/env python3
"""
Builds search-index.js from the article pages.

Run this whenever you add or edit an article:

    python3 build-search-index.py

What it does:
  1. Gives every <h3> an id, derived from its text, so results can deep-link
     to an individual question or subsection rather than a whole page.
  2. Extracts the plain text of every section (h2 and h3) from each article.
  3. Writes search-index.js, which the search box on the home page reads.

The index is written as a .js file rather than .json so the site still works
when opened directly from disk, where fetch() would be blocked.
"""

import glob
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "search-index.js")
SKIP = {"index.html"}


def slugify(text, taken):
    slug = re.sub(r"<[^>]+>", "", text).lower()
    slug = slug.replace("&amp;", "and").replace("&nbsp;", " ")
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s-]+", "-", slug).strip("-")[:60] or "section"
    candidate, n = slug, 2
    while candidate in taken:
        candidate, n = f"{slug}-{n}", n + 1
    taken.add(candidate)
    return candidate


def strip_tags(fragment):
    """Plain text, with citation markers and evidence tags removed."""
    text = re.sub(r"<sup class=\"cite\">.*?</sup>", "", fragment, flags=re.S)
    text = re.sub(r"<span class=\"tag[^\"]*\">.*?</span>", "", text, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def add_missing_h3_ids(source):
    """Give every <h3> an id so results can link straight to it."""
    taken = set(re.findall(r'<h[23] id="([^"]+)"', source))
    out, cursor = [], 0
    for match in re.finditer(r"<h3(?![^>]*\bid=)([^>]*)>(.*?)</h3>", source, flags=re.S):
        out.append(source[cursor:match.start()])
        out.append(f'<h3 id="{slugify(match.group(2), taken)}"{match.group(1)}>{match.group(2)}</h3>')
        cursor = match.end()
    out.append(source[cursor:])
    return "".join(out)


def build_records(filename, source):
    title_match = re.search(r"<h1>(.*?)</h1>", source, flags=re.S)
    kicker_match = re.search(r'<p class="kicker">.*?>([^<]+)</a>', source, flags=re.S)
    title = strip_tags(title_match.group(1)) if title_match else filename
    category = kicker_match.group(1).strip() if kicker_match else ""

    # Only index the article body, not the nav, contents list or footer.
    start = source.find('id="article-body"')
    end = source.find('<aside class="disclaimer')
    if start == -1:
        return []
    body = source[start:end if end != -1 else len(source)]

    headings = list(re.finditer(r'<(h2|h3) id="([^"]+)"[^>]*>(.*?)</\1>', body, flags=re.S))
    records, section = [], ""

    # A page with no headings at all — the essay, for instance — still needs to be
    # searchable. Index it as one record pointing at the top of the article.
    if not headings:
        text = strip_tags(body)
        # Skip placeholder pages, so "not yet written" never shows up as a result.
        if len(text) < 200:
            return []
        return [{
            "f": filename,
            "a": "article-body",
            "t": title,
            "c": category,
            "s": "",
            "h": title,
            "x": text,
        }]

    for i, match in enumerate(headings):
        level, anchor, heading_html = match.group(1), match.group(2), match.group(3)
        heading = strip_tags(heading_html)
        if level == "h2":
            section = heading
        stop = headings[i + 1].start() if i + 1 < len(headings) else len(body)
        text = strip_tags(body[match.end():stop])
        if not text:
            continue
        records.append({
            "f": filename,
            "a": anchor,
            "t": title,
            "c": category,
            "s": section if level == "h3" else "",
            "h": heading,
            "x": text,
        })
    return records


def main():
    index = []
    for path in sorted(glob.glob(os.path.join(HERE, "*.html"))):
        filename = os.path.basename(path)
        if filename in SKIP:
            continue
        with open(path, encoding="utf-8") as handle:
            source = handle.read()

        updated = add_missing_h3_ids(source)
        if updated != source:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(updated)
            source = updated

        records = build_records(filename, source)
        index.extend(records)
        print(f"{filename:34s} {len(records):3d} sections")

    payload = json.dumps(index, ensure_ascii=False, separators=(",", ":"))
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("/* Generated by build-search-index.py — do not edit by hand. */\n")
        handle.write(f"window.SEARCH_INDEX = {payload};\n")

    size = os.path.getsize(OUTPUT) / 1024
    print(f"\n{len(index)} sections indexed → search-index.js ({size:.0f} KB)")


if __name__ == "__main__":
    main()
